# --- Note, the following list may not be exhaustive. Check the relevant CEBRA implementation for a full list of the hyperparameters ---  

model_architecture = "offset1-model"            # string
device = "cuda_if_available"                    # string
criterion = "infonce"                           # string
distance = "euclidean"                          # string
#conditional = None                             # string
temperature = 1.0                               # float
temperature_mode = "constant"                   # Literal("constant", "auto")
min_temperature = 0.1                           # float
time_offsets = 1                                # int
#delta = None                                   # float
max_iterations = 1000                           # int
max_adapt_iterations = 250                      # int
#batch_size = None                              # int
learning_rate = 3e-3                            # float
optimizer = "adam"                              # string
output_dimension = 8                            # int
verbose = false                                 # bool
num_hidden_units = 32                           # int
pad_before_transform = true                     # bool
hybrid = false                                  # bool

[optimizer_kwargs]
    betas = [0.9, 0.999]                        # Tuple[float, float]
    eps = 1e-08                                 # float
    weight_decay = 0                            # float
    amsgrad = false                             # bool