host = '127.0.0.1'
port = 8082
dashboard-host = '127.0.0.1'
dashboard-port = 8007

data-stream-name = 'mockup_random'
stream-buffer-size-s = 0.05

labels = [
    'a',
    'b',
    'c',
    'd'
]
unclassified-label = 'unclassified'


hyperparameter-config-folder = './configs/hyperparameters'
[hyperparameter-config-files]
    UMAP = 'hyperparameters_umap.toml'
    UMAP_Approx = 'hyperparameters_umap.toml'
    CEBRA = 'hyperparameters_cebra.toml'


[projector-settings]
    projection-method = 'UMAP_Approx'
    align-projections = false
    use-mock-data = true
    min-training-samples-to-start-projecting = 5
    max-sampling-frequency = 10
    max-model-update-frequency = 0.1


[plot-settings]
    scatter-point-size = 6
    point-selection-border-size = 2
    point-selection-border-color = 'DarkSlateGrey'
    point-highlight-size = 10
    point-highlight-border-size = 1
    point-highlight-border-color = 'DarkSlateGrey'

    unclassified-label-color = 'gray'
    min-opacity =  0.25
    show-axis =  false
    transition-duration = 500
    
    [plot-settings.label-colors]
        a = 'blue'
        b = 'red'
        c = 'green'

    [plot-settings.opacity-thresholds]
        '1' = 20
        '0.75' = 20
        '0.5' = 20

    [plot-settings.default-x-range]
        start = -0.2
        end = 1.2
    [plot-settings.default-y-range]
        start = -0.2
        end = 1.2


[dashboard-settings]
    graph-refresh-frequency = 2


# The stream settings can be ratjer complex for a novel user.
# Please look at the streaming section of the user guide for an explination on how to set the following config correctly.
[stream-settings]
    feature-stream-name = 'Features'
    auxiliary-stream-name = 'Classifier'
    stream-buffer-size-s = 10
    
    feature-section = 'features'

    watch-labels = true
    label-section = 'ground truth labels'
    labels-from-auxiliary-stream = false
    label-interpretation-method = "one-to-one"

    match-by-sample-id = false
    label-feature-matching-scheme = 'match-samples'

    auxiliary-stream-drift-ms = 0

    [stream-settings.feature-stream-layout]
        id-index = ''

        [stream-settings.feature-stream-layout.section.features]
            section-name = 'features'
            start-index = 0
            length = 10

        [stream-settings.feature-stream-layout.section.ground-truth-label]
            section-name = 'ground truth labels'
            start-index = 10
            length = 1

    [stream-settings.auxiliary-stream-layout]
        id-index = ''

        [stream-settings.auxiliary-stream-layout.section.classification-results]
            section-name = 'classification results'
            start-index = 0
            length = 3
