[python]
# Modules to be brought up by simply running the python processes async
# Leave this empty if no blocks should be started like this
modules_root = '../'                                                            # path to the root if the modules

# -------------------- Mockup Streamer ---------------------------------------
[python.modules.dp-mockup-streamer]                                      # names of a module to be used (folder name)
    type = 'io_data'
    port = 8081                                                                 # if no port is provided, a random free port is chosen
    ip = '127.0.0.1'
[python.modules.dp-mockup-streamer.kwargs]                               # kwargs to run the main script with
    lsl_out_stream_name = 'mockup_EEG_stream'
    # random_data = true --> use the start random button!

# -------------------- ONEP ---------------------------------------
[python.modules.ONEP]                                      # names of a module to be used (folder name)
    port = 8082                                                                 # if no port is provided, a random free port is chosen
    ip = '127.0.0.1'